# Generated by Django 4.2.9 on 2024-01-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_creation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreationmodel',
            name='academic_degrees',
            field=models.CharField(default='bac', max_length=255, verbose_name='Academic degrees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='current_employment',
            field=models.CharField(default='student', max_length=255, verbose_name='current employment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='date_naissance',
            field=models.DateField(default='1993-10-25', verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='description',
            field=models.CharField(default='student', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='hobbies',
            field=models.CharField(default='watching movies', max_length=255, verbose_name='hobbies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='lieu_residence',
            field=models.CharField(default='tunisia', max_length=255, verbose_name='Place of residence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='professional_skills',
            field=models.CharField(default='tunisia', max_length=255, verbose_name='professional skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreationmodel',
            name='social_media',
            field=models.CharField(default='', max_length=50, verbose_name='social media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercreationmodel',
            name='image_title',
            field=models.CharField(default='profil photo', max_length=100, verbose_name='Profile picture'),
        ),
    ]
